<br />
<br />
<br />
<fieldset>
<legend>:: Downloads de relatórios</legend>
<br />
<a href="<?=$this->download_url?>relatorio_declaracoes_mensais.csv"><img src="./img/icone-excel.jpg" border="0">&nbsp;&nbsp;Relatório de Declarações Mensais Realizadas</a>
<br />
<br />
<a href="<?=$this->download_url?>relatorio_declaracoes_mensais_nao_transmitidas.csv"><img src="./img/icone-excel.jpg" border="0">&nbsp;&nbsp;Relatório de Declarações Mensais Não Realizadas</a>
</fieldset>