<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
	<base href="<?= (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on' ? 'https' : 'http') ?>://<?=$_SERVER['HTTP_HOST'] ?><?= Zend_Registry::get('config')->html->base ?>" />

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>SIGICMS</title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<script src="assets/javascripts/1.2.2/adminflare-demo-init.min.js" type="text/javascript"></script>
	<script src="assets/javascripts/1.2.2/modernizr-jquery.min.js" type="text/javascript"></script>
	<script src="assets/javascripts/1.2.2/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/javascripts/1.2.2/adminflare-demo.min.js" type="text/javascript"></script>
	<script src="assets/javascripts/1.2.2/adminflare.min.js" type="text/javascript"></script>

	<script src="js/layout/layout.js" type="text/javascript"></script>
	<script src="js/default.js" type="text/javascript"></script>
	<script src="js/jquery.maskedinput-1.2.2.min.js" type="text/javascript"></script>
	<script src="js/bootstrap-datepicker.js" type="text/javascript"></script>

	<link rel="stylesheet" type="text/css" href="css/layout/layout.css" />

	<?php echo $this->headScript(); ?>

	<?php echo $this->headLink(); ?>

</head>

<body>
	<script type="text/javascript">demoSetBodyLayout();</script>
	<!-- Main navigation bar
		================================================== -->
	<header class="navbar navbar-fixed-top" id="main-navbar">
		<div class="navbar-inner">
			<div class="container">
				<a class="logo" href="#"><img alt="Af_logo" src="assets/images/af-logo.png"></a>

				<div class="nav-collapse collapse">
					<ul class="nav">

						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Manutenção
								<i class=" icon-caret-down"></i>
							</a>
							<ul class="dropdown-menu">
								<li><a href="<?= $this->url(array('controller' => 'contribuinte', 'action' => 'inserir'), null, true) ?>">Cadastro de Contribuintes</a></li>
								<li><a href="<?= $this->url(array('controller' => 'contribuinte', 'action' => 'listagem'), null, true) ?>">Manutenção de Contribuintes</a></li>
								<li><a href="<?= $this->url(array('controller' => 'contribuinte', 'action' => 'upload-lote'), null, true) ?>">Importação Lote de Contribuintes</a></li>

								<li class="divider"></li>

								<li><a href="<?= $this->url(array('controller' => 'contador', 'action' => 'inserir'), null, true) ?>">Cadastro de Contadores</a></li>
								<li><a href="<?= $this->url(array('controller' => 'contador', 'action' => 'listagem'), null, true) ?>">Manutenção de Contadores</a></li>

							</ul>
						</li>

						<li class="divider-vertical"></li>
					</ul>
					<ul class="nav pull-right">
						<!-- li>
							<ul class="messages">
								<li><a href="#"><i class="icon-warning-sign"></i> 2<span
										class="		responsive-text"> alerts</span></a></li>
								<li><a href="#"><i class="icon-envelope"></i> 25<span
										class="		responsive-text"> new messages</span></a></li>
							</ul>
						</li -->
						<li class="separator"></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle usermenu" data-toggle="dropdown">
								<img alt="Avatar" src="assets/images/avatar.png">
								<span>&nbsp;&nbsp;<?= $this->objZendDbTableRowPessoa->descri ?></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">Alterar Cadastro</a></li>
								<li><a href="#">Alterar Senha</a></li>
								<li class="divider"></li>
								<li><a href="/">Sair</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</header>
	<!-- / Main navigation bar -->

	<!-- Left navigation panel
		================================================== -->
	<nav id="left-panel">
		<div id="left-panel-content">
			<ul>
				<li class="active"><a href="dashboard.html"><span
						class="icon-dashboard"></span>Dashboard</a></li>
				<li><a href="layout.html"><span class="icon-th-large"></span>Layout</a>
				</li>
				<li><a href="typography.html"><span class="icon-font"></span>Typography</a>
				</li>
				<li><a href="forms.html"><span class="icon-edit"></span>Forms</a></li>
				<li><a href="tables.html"><span class="icon-table"></span>Tables</a>
				</li>

				<li><a href="components.html"><span class="icon-inbox"></span>Components</a>
				</li>

				<li class="lp-dropdown"><a href="#" class="lp-dropdown-toggle"
					id="extras-dropdown"><span class="icon-reorder"></span>Extras</a>
					<ul class="lp-dropdown-menu" data-dropdown-owner="extras-dropdown">
						<li><a tabindex="-1" href="extras-icons.html"><span
								class="icon-coffee"></span>Icons</a></li>
						<li><a tabindex="-1" href="extras-charts.html"><span
								class="icon-bar-chart"></span>Charts</a></li>
						<li><a tabindex="-1" href="extras-widgets.html"><span
								class="icon-star"></span>Widgets</a></li>
					</ul></li>
				<li class="lp-dropdown"><a href="#" class="lp-dropdown-toggle"
					id="pages-dropdown"><span class="icon-file-alt"></span>Pages</a>
					<ul class="lp-dropdown-menu simple"
						data-dropdown-owner="pages-dropdown">
						<li><a tabindex="-1" href="index.html"><i class="icon-signin"></i>&nbsp;&nbsp;Sign
								In</a></li>
						<li><a tabindex="-1" href="pages-signup.html"><i
								class="icon-check"></i>&nbsp;&nbsp;Sign Up</a></li>
						<li><a tabindex="-1" href="pages-messages.html"><i
								class="icon-envelope-alt"></i>&nbsp;&nbsp;Messages</a></li>
						<li><a tabindex="-1" href="pages-stream.html"><i class="icon-leaf"></i>&nbsp;&nbsp;Stream</a>
						</li>
						<li><a tabindex="-1" href="pages-pricing.html"><i
								class="icon-money"></i>&nbsp;&nbsp;Pricing</a></li>
						<li><a tabindex="-1" href="pages-invoice.html"><i
								class="icon-pencil"></i>&nbsp;&nbsp;Invoice</a></li>
					</ul></li>
			</ul>
		</div>
		<div class="icon-caret-down"></div>
		<div class="icon-caret-up"></div>
	</nav>
	<!-- / Left navigation panel -->

	<section class="container" style="border: 0px solid;">
		<?php
		if(isset($this->arrParams['erro']) && count($this->arrParams['erro']))
			foreach($this->arrParams['erro'] as $strErro)
				print '<div class="alert alert-error"><a href="#" class="close" data-dismiss="alert">x</a>' . $strErro . '</div>';

		if(isset($this->arrSucesso[0]) && trim($this->arrSucesso[0]) != '')
				print '<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">x</a>' . $this->arrSucesso[0] . '</div>';

		echo $this->layout()->content;
		?>
	</section>


</body>
</html>