<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
	<base href="<?= (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on' ? 'https' : 'http') ?>://<?=$_SERVER['HTTP_HOST'] ?><?= Zend_Registry::get('config')->html->base ?>" />

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title> SIGICMS </title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<script src="assets/javascripts/1.2.2/adminflare-demo-init.min.js" type="text/javascript"></script>
	<script src="assets/javascripts/1.2.2/modernizr-jquery.min.js" type="text/javascript"></script>

	<script src="js/layout/logout.js" type="text/javascript"></script>
	<script src="js/default.js" type="text/javascript"></script>
	<script src="js/jquery.maskedinput-1.2.2.min.js" type="text/javascript"></script>
	<script src="js/bootstrap-datepicker.js" type="text/javascript"></script>

	<link rel="stylesheet" type="text/css" href="css/layout/logout.css" />

	<?php echo $this->headScript(); ?>

	<?php echo $this->headLink(); ?>

	<!--[if lte IE 9]>
		<script src="/assets/javascripts/jquery.placeholder.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			$(document).ready(function () {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->

</head>
<body>

	<!-- Main navigation bar
		================================================== -->
	<header class="navbar navbar-fixed-top" id="main-navbar">
		<div class="navbar-inner">
		</div>
	</header>

	<?php
	if(isset($this->arrParams['erro']) && count($this->arrParams['erro']))
		foreach($this->arrParams['erro'] as $strErro)
			print '<div class="alert alert-error" style="margin-top: 45px;"><a href="#" class="close" data-dismiss="alert">x</a>' . $strErro . '</div>';

	if(isset($this->arrSucesso[0]) && trim($this->arrSucesso[0]) != '')
			print '<br /><br /><div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">x</a>' . $this->arrSucesso[0] . '</div>';

	echo $this->layout()->content;
	?>

</body>
</html>