<section class="signin-container" style="border: 0px solid;">

	<div style="border: 0px solid; text-align: center;">
		<span style="font-size: 22px;"><b>IPM - On Line</b> </span>
		<br /><br />
	</div>
	
	<div>
		<form method="post" action="<?= $this->url(array('controller' => 'login', 'action' => 'logar')); ?>">
			<fieldset>
				<div>
					<input type="text" id="usuario" name="usuario" value="<?= (isset($this->arrParams['usuario']) ? $this->arrParams['usuario'] : '') ?>" placeholder="Usuário" tabindex="1" />

					<input type="password" id="password" name="senha" placeholder="Senha" tabindex="2" />
				</div>
				<a href="<?= $this->url(array('controller' => 'login', 'action' => 'esqueci-minha-senha')) ?>" title="" tabindex="3" class="forgot-password">...esqueci</a>
				<button type="submit" class="btn btn-primary btn-block" tabindex="4">Logar</button>
			</fieldset>
		</form>
		
		<br />
		
		<div style="border: 0px solid;">
			<a href="<?= $this->url(array('controller' => 'cadastro', 'action' => 'index')) ?>">Cadastro de contadores e contribuintes</a> 
			 
		</div>
		<div style="border: 0px solid;">
			<a href="<?= $this->url(array('controller' => 'esqueci-minha-senha', 'action' => 'esqueci-minha-senha')) ?>">Esqueci minha senha</a>
		</div>
	</div>
</section>


