<table class="table table-striped table-bordered" border="0">

	<thead>
		<tr>
			<th>CPF/CNPJ</th>
			<th>Inscr.Estadual</th>
			<th>Nome/Razão Social</th>
			<th>Regime</th>
			<?php 
			if($this->intTipoControle == 1) {
			?>
				<th style="text-align: center;">Editar</th>
				<th style="text-align: center;">Excluir</th>
				<th style="text-align: center;">Notificar</th>
			<?
			} elseif($this->intTipoControle == 2) { 
			?>
				<th style="text-align: center;">Remover</th>
			<?php 
			}
			?>				
			

		</tr>
	</thead>

	<?php 
	if(!(boolean)$this->objZendDbTableRowsetContribuinte->count()) {
	?>
		<tbody><tr><td colspan="7" style="text-align: center;"> <b> --- Sem resultado --- </b> </td></tr></tbody>
	<?php
	} else { 
	?>
		<tbody>
			<?php
			foreach($this->objZendDbTableRowsetContribuinte as $objZendDbTableRowContribuinte) {
				$objZendDbTableRowPessoa = $objZendDbTableRowContribuinte->findParentEntity_Pessoa();
				$objZendDbTableRowRegime = $objZendDbTableRowContribuinte->findParentEntity_Regime();
				?>
				<tr>
					<td><?=$objZendDbTableRowPessoa->cpf_cnpj?></td>
					<td><?=$objZendDbTableRowContribuinte->inscricao_estadual?></td>
					<td><?=$objZendDbTableRowPessoa->descri?></td>
					<td><?=$objZendDbTableRowRegime->descri?></td>
					
					<?php 

					if($this->intTipoControle == 1) {
					?>
						<td style="text-align: center;"> 
							<a class="btn btn-primary" href="<?= $this->url(array('controller' => 'contribuinte', 'action' => 'alterar', 'id' => base64_encode($objZendDbTableRowContribuinte->id)), null, true) ?> ">
								<i class="icon-edit icon-large"></i> 
							</a>
	  					</td>
						<td style="text-align: center;">
							<a href="#" class="btn btn-primary" onClick="excluir('<?= base64_encode($objZendDbTableRowContribuinte->id) ?>', '<?= $objZendDbTableRowPessoa->descri ?>'); return false;">
								<i class="icon-trash icon-large"></i> 
							</a>
						</td>
						<td style="text-align: center;"> 
							<a href="#" class="btn btn-primary" onClick="alert('Em desenvolvimento'); return false;">
								<i class="icon-envelope icon-large"></i> 
							</a>
						</td>
					<?php
					} elseif($this->intTipoControle == 2) { 
					?>
						<td style="text-align: center;"> 
							<a href="#" class="btn btn-primary" onClick="alert('Em desenvolvimento'); return false;">
								<i class="icon-remove-sign"></i> 
							</a>
						</td>
					<?php 
					}
					?>						
				</tr>
			<?php 
			}
			?>
		</tbody>
	<?php
	}
	?>	
	
</table>
	
	
