<section class="container">

	<div style="background-color: #FFFFFF; border: 0px solid;" >
	
		<h1 class="page-title">
			<span> Cadastro concluído </span>
		</h1>
									
	
		<span style="margin-left: 35px; margin-bottom: 10px;">
			Cadastro enviado com sucesso. Em breve você receberá um e-mail com o resultado da sua solicitação.
		</span>
		
		<div class="controls" style="margin-top: 20px;">
			<button class="btn btn-primary" onClick="location.href = '<?= $this->url(array('controller' => 'login', 'action' => 'login')) ?>'; return false;" style="margin-left: 50px; margin-bottom: 30px;">Voltar à página de login</button>
			<button class="btn" onClick="alert('Em desenvolvimento'); " style="margin-left: 20px; margin-bottom: 30px;">Fechar esta janela</button>
		</div>
		
	</div>
	
</section>