<section class="container">
<div style="background-color: #FFFFFF; border: 0px solid;">

	<h1 class="page-title">
		<span> Contribuinte </span>
	</h1>
								
	<form class="form-horizontal" method="post" action="<?= $this->url(array('controller' => 'cadastro', 'action' => 'receber-inscricao')); ?>">
		<fieldset>
			
			<div class="control-group">
				<label class="control-label"><span style="color: #8B1A1A;">*</span>&nbsp;Inscrição Estadual</label>
				<div class="controls">
					<input type="text" id="inscricao_estadual" name="inscricao_estadual" value="<?= (isset($this->arrParams['inscricao_estadual']) ? $this->arrParams['inscricao_estadual'] : ''); ?>" placeholder="Somente números" style="width: 175px;" />
					<p class="help-block"></p>
				</div>
			</div>
		
			<button type="submit" class="btn btn-primary" style="margin-left: 50px; margin-bottom: 30px; width: 120px;">Próximo passo</button>
			<button class="btn" style="margin-left: 20px; margin-bottom: 30px; width: 120px;" onClick="location.href = '<?= $this->url(array('controller' => 'cadastro', 'action' => 'opcoes')) ?>'; return false;">Voltar</button>
			
			<br /> 

		</fieldset>
	</form>

</div>
</section>